server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  thymeleaf:
    encoding: UTF-8
    cache: false
  data:
    mongodb:
      # Use EITHER this single URI (recommended)...
      uri: mongodb://localhost:27017/mindChatBotDB
      # ...OR the individual host/port/credentials keys below (NOT BOTH).

  web:
    resources:
      static-locations: classpath:/static/

openai:
  api:
    # read from env if set
  model: gpt-4o-mini           # use whatever your service expects
  system:
    prompt: |
      You are a kind, emotionally smart mental health assistant.
      Keep replies short, casual, and friendly—like social media messages.
      Listen well and respond with empathy without repeating yourself.
      Encourage sharing, but don’t push.

jwt:

