server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  thymeleaf:
    encoding: UTF-8
    cache: false
  data:
    mongodb:
      # 🚨 FIXED: Removed the local fallback. 
      # The app will now crash if MONGO_URI is not set in the environment,
      # ensuring it always uses the Atlas URI in the cloud.
      uri: ${MONGO_URI}
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: mindchatbotst@gmail.com
    # Keep using the environment variable for security
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: "classpath:/static/"

openai:
  api:
    # Keep using the environment variable
    key: ${OPENAI_API_KEY}
  model: "gpt-4o-mini"
  system:
    prompt: |
      You are a kind, emotionally smart mental health assistant.
      Keep replies short, casual, and friendly—like social media messages.
      Listen well and respond with empathy without repeating yourself.
      Encourage sharing, but don’t push.

jwt:
  # Keep using the environment variable
  secret: ${JWT_SECRET_KEY}
logging:
  level:
    org.springframework.security: INFO
    MindChatBot.mindChatBot: INFO